jardineria/jardineria/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jardineria_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

jardineria/jardineria_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    detalle_pedido, flores, base, maceteros, listar_usuarios, detalles_usuario, modificar_usuario, suculentas, sustratos, tierra, home, seguimiento_pedido,
    crearcuenta, salir, producto, crearproducto, detalles_producto, modificarproducto, agregar_a_pedido, pedidoscli, actualizar_cantidad, eliminar_pedido, listar_usuarios_con_pedidos, detalles_pedidos_usuario, agregar_pedido_usuario
)

urlpatterns = [
    # Home
    path('', home, name='home'),
    path('base/', base, name='base'),

    # Usuarios
    path('usuarios/', listar_usuarios, name='listar_usuarios'),
    path('usuarios/<int:user_id>/', detalles_usuario, name='detalles_usuario'),
    path('usuarios/<int:user_id>/modificar/', modificar_usuario, name='modificar_usuario'),
    path('crearcuenta/', crearcuenta, name='crearcuenta'),
    path('salir/', salir, name='salir'),
    
    # Usuarios con pedidos
    path('usuarios_con_pedidos/', listar_usuarios_con_pedidos, name='listar_usuarios_con_pedidos'),
    path('usuarios_con_pedidos/<int:user_id>/', detalles_pedidos_usuario, name='detalles_pedidos_usuario'),
    path('usuarios_con_pedidos/<int:user_id>/agregar_pedido/', agregar_pedido_usuario, name='agregar_pedido_usuario'),

    # Pedidos
    path('pedidoscli/', pedidoscli, name='pedidoscli'),
    path('detalle_pedido/', detalle_pedido, name='detalle_pedido'),
    path('agregar_a_pedido/<str:producto_id>/', agregar_a_pedido, name='agregar_a_pedido'),
    path('actualizar_cantidad/<int:pedido_id>/', actualizar_cantidad, name='actualizar_cantidad'),
    path('eliminar_pedido/<int:pedido_id>/', eliminar_pedido, name='eliminar_pedido'),
    path('seguimiento_pedido/', seguimiento_pedido, name='seguimiento_pedido'),

    # Productos
    path('productos/', producto, name='productos'),
    path('detalles_producto/<id>', detalles_producto, name='detalles_producto'),
    path('modificarproducto/<id>', modificarproducto, name='modificarproducto'),
    path('crearproducto/', crearproducto, name='crearproducto'),

    # Otros
    path('flores/', flores, name='flores'),
    path('maceteros/', maceteros, name='maceteros'),
    path('suculentas/', suculentas, name='suculentas'),
    path('sustratos/', sustratos, name='sustratos'),
    path('tierra/', tierra, name='tierra'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jardineria/jardineria_app/models.py
#models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from .tipos import *
from django.contrib.auth.models import AbstractUser
from django.conf import settings

class User(AbstractUser):
    rut=models.CharField(max_length=10, null=False)
    direccion=models.CharField(max_length=500, null=False)

class Persona(models.Model):
    rut=models.CharField(max_length=10, primary_key=True)
    username=models.CharField(max_length=20, null=False)
    first_name=models.CharField(max_length=50, null=False)
    last_name=models.CharField(max_length=50, null=False)
    direccion=models.CharField(max_length=100, null=False)
    email=models.EmailField(max_length=100, null=False)
    
    def __str__(self):
        return f"{self.rut} - {self.nombre} {self.apellido}"
    
class Producto (models.Model):
    codigo_producto=models.CharField(max_length=50,primary_key=True)
    nombre_producto=models.CharField(max_length=50, null=False)
    cantidad=models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(250)])
    tipo=models.CharField(max_length=25, choices=TIPO_PRODUCTO)
    precio=models.IntegerField(validators=[MinValueValidator(1000),MaxValueValidator(10000000)])
    imagen=models.ImageField(upload_to='producto', null=True)
    def __str__(self):
        return f"{self.codigo_producto} - {self.nombre_producto} {self.cantidad} {self.tipo}"
    
class Pedido(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Pedido de {self.usuario.username} - {self.producto.nombre_producto}"

jardineria/jardineria_app/views.py
#views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.views import View
from .forms import  UserForm,ProductoForm,UpdProductoForm,UpdUserForm
from django.contrib import messages
from django.contrib.auth import logout, get_user_model
#from django.contrib.auth.models import User
from jardineria_app.models import User
from .models import Producto,Pedido
from .tipos import TIPO_PRODUCTO
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect



@login_required
def flores(request):
    productos_flores = Producto.objects.filter(tipo='FLORES')
    datos = {
        "productos_flores": productos_flores
    }
    return render(request, 'crud/flores.html', datos)
@login_required
def maceteros(request):
    productos_maceteros = Producto.objects.filter(tipo='MACETEROS')
    datos = {
        "productos_maceteros": productos_maceteros
    }
    return render(request, 'crud/maceteros.html', datos)
@login_required
def suculentas(request):
    productos_suculentas = Producto.objects.filter(tipo='SUCULENTAS')
    datos = {
        "productos_suculentas": productos_suculentas
    }
    return render(request, 'crud/suculentas.html', datos)
@login_required
def sustratos(request):
    productos_sustratos = Producto.objects.filter(tipo='SUSTRATOS')
    datos = {
        "productos_sustratos": productos_sustratos
    }
    return render(request, 'crud/sustratos.html', datos)
@login_required
def tierra(request):
    productos_tierras = Producto.objects.filter(tipo='TIERRA DE HOJA')
    datos = {
        "productos_tierras": productos_tierras
    }
    return render(request, 'crud/tierra.html', datos)
### FUNCIONES DE PRODUCTOS-------------------------############################################################
def producto (request):
    producto=Producto.objects.all()

    datos={
        "producto":producto
    }
    return render(request,'crud/productos.html', datos)

@permission_required('jardineria.add_producto')
def crearproducto(request):
    formulario=ProductoForm()
    if request.method=="POST":
        formulario=ProductoForm(request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            #from django.contrib import messages
            messages.set_level(request,messages.SUCCESS)
            messages.success(request, "Producto creado con exito!!!")
            return redirect(to="productos")
        
    datos={
        "formulario":formulario
    }
    return render(request,'crud/crearproducto.html', datos)
@login_required
def detalles_producto(request, id):
    #persona=Persona.objects.get(rut=id)
    producto=get_object_or_404(Producto,codigo_producto=id)
    datos={
        "producto":producto
    }
    return render(request,'crud/detalles_producto.html',datos)
@permission_required('jardineria.change_producto')
def modificarproducto(request,id):
    producto=get_object_or_404(Producto, codigo_producto=id)
    form=UpdProductoForm(instance=producto)
    if request.method=="POST":
         form=UpdProductoForm(request.POST, files=request.FILES, instance=producto)
         if form.is_valid():
             form.save()
             messages.set_level(request,messages.WARNING)
             messages.warning(request,"Producto modificado")
             return redirect(to="productos")
    datos={
        'producto':producto,
        'form':form
    }
    return render(request,'crud/modificarproducto.html',datos)
### FUNCIONES DE PEDIDO-------------------------############################################################
@login_required
def seguimiento_pedido(request):
    pedidos = Pedido.objects.filter(usuario=request.user)
    detalles_pedidos = []

    for pedido in pedidos:
        subtotal = pedido.producto.precio * pedido.cantidad
        detalles_pedidos.append({
            'producto': pedido.producto,
            'cantidad': pedido.cantidad,
            'subtotal': subtotal,
        })
    
    total_pedido = sum(item['subtotal'] for item in detalles_pedidos)
    
    context = {
        'detalles_pedidos': detalles_pedidos,
        'total_pedido': total_pedido,
        'usuario': request.user,
    }
    
    return render(request, 'crud/seguimiento_pedido.html', context)

@login_required
def detalle_pedido(request):
    pedidos = Pedido.objects.filter(usuario=request.user)
    
    total_pedido = 0
    detalles_pedidos = []
    for pedido in pedidos:
        subtotal = pedido.producto.precio * pedido.cantidad
        total_pedido += subtotal
        detalles_pedidos.append({
            'producto': pedido.producto,
            'cantidad': pedido.cantidad,
            'subtotal': subtotal,
        })
    
    context = {
        'detalles_pedidos': detalles_pedidos,
        'total_pedido': total_pedido,
        'usuario': request.user,
    }
    
    return render(request, 'crud/detalle_pedido.html', context)
@login_required
def agregar_a_pedido(request, producto_id):
    producto = get_object_or_404(Producto, pk=producto_id)
    usuario = request.user
    cantidad = 1  # Aquí puedes adaptar la lógica para obtener la cantidad deseada

    pedido, created = Pedido.objects.get_or_create(usuario=usuario, producto=producto, defaults={'cantidad': cantidad})
    if not created:
        pedido.cantidad += 1
        pedido.save()

    messages.success(request, f"{producto.nombre_producto} ha sido agregado a tu pedido!")
    return redirect('pedidoscli')  # Redirigir a la vista de pedidos del cliente
@login_required
def pedidoscli(request):
    pedidos = Pedido.objects.filter(usuario=request.user)
    
    total_pedido = sum(pedido.producto.precio * pedido.cantidad for pedido in pedidos)
    
    context = {
        'pedidos': pedidos,
        'total_pedido': total_pedido,
    }
    
    return render(request, 'crud/pedidoscli.html', context)

@login_required
def actualizar_cantidad(request, pedido_id):
    pedido = get_object_or_404(Pedido, pk=pedido_id, usuario=request.user)
    if request.method == "POST":
        nueva_cantidad = int(request.POST.get('cantidad'))
        if nueva_cantidad > 0 and nueva_cantidad <= pedido.producto.cantidad:
            pedido.cantidad = nueva_cantidad
            pedido.save()
            messages.success(request, "Cantidad actualizada correctamente.")
        else:
            messages.error(request, "Cantidad inválida.")
    return redirect('pedidoscli')

@login_required
def eliminar_pedido(request, pedido_id):
    pedido = get_object_or_404(Pedido, pk=pedido_id, usuario=request.user)
    if request.method == "POST":
        pedido.delete()
        messages.success(request, "Producto eliminado del pedido.")
    return redirect('pedidoscli')

### FUNCIONES DE USUARIO-------------------------############################################################
def crearcuenta(request):
    form=UserForm()
    if request.method=="POST":
        form=UserForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="home")
    datos={
        "form":form
    }
    return render(request, 'registration/crearcuenta.html',datos)

@login_required
@permission_required('auth.view_user')
def listar_usuarios(request):
    User = get_user_model()
    usuarios = User.objects.all()
    datos = {
        "usuarios": usuarios
    }
    return render(request, 'crud/usuarios.html', datos)

@login_required
@permission_required('auth.view_user')
def detalles_usuario(request, user_id):
    User = get_user_model()
    usuario = get_object_or_404(User, id=user_id)
    datos = {
        "usuario": usuario
    }
    return render(request, 'crud/detalles_usuario.html', datos)

@login_required
@permission_required('auth.change_user', raise_exception=True)
def modificar_usuario(request, user_id):
    User = get_user_model()
    usuario = get_object_or_404(User, id=user_id)
    
    if request.method == 'POST':
        form = UpdUserForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect('detalles_usuario', user_id=user_id)  # Redirecciona al detalle del usuario modificado
    else:
        form = UpdUserForm(instance=usuario)
    
    datos = {
        'form': form
    }
    return render(request, 'crud/modificar_usuario.html', datos)

def salir(request):
    logout(request)
    return redirect(to='home')


def admin_page(request):
    return render(request, 'crud/administrador.html')


def base(request):
    return render(request, 'crud/base.html')


def home(request):
    return render(request, 'crud/home.html')

#########################################funciones para controles de pedido de usuarios

@login_required
@permission_required('auth.view_user')
def listar_usuarios_con_pedidos(request):
    usuarios_con_pedidos = User.objects.filter(pedido__isnull=False).distinct()
    datos = {
        "usuarios": usuarios_con_pedidos
    }
    return render(request, 'crud/usuarios_con_pedidos.html', datos)

@login_required
@permission_required('auth.view_user')
def detalles_pedidos_usuario(request, user_id):
    usuario = get_object_or_404(User, id=user_id)
    pedidos = Pedido.objects.filter(usuario=usuario)
    
    detalles_pedidos = []
    total_pedido = 0

    for pedido in pedidos:
        subtotal = pedido.producto.precio * pedido.cantidad
        total_pedido += subtotal
        detalles_pedidos.append({
            "pedido": pedido,
            "producto": pedido.producto,
            "cantidad": pedido.cantidad,
            "subtotal": subtotal
        })

    if request.method == "POST":
        action = request.POST.get("action")
        if action == "modificar":
            pedido_id = request.POST.get("pedido_id")
            cantidad = int(request.POST.get("cantidad"))
            pedido = get_object_or_404(Pedido, id=pedido_id)
            pedido.cantidad = cantidad
            pedido.save()

jardineria/jardineria_app/templates/crud/crearproducto.html
{% extends "crud/base.html" %}
{% load static %}
{% load crispy_forms_tags %}



{% block contenido %}
<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="p-5 border rounded shadow mt-4">
                <h3>Crear Producto</h3>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{formulario | crispy}}

                    <div>
                        <input type="submit" value="Guardar Producto" class="btn btn-success btn-lg">
                        <a href="{% url "productos" %}">
                            <button type="button" class="btn btn-light border btn-lg">Volver</button>
                        </a>
                    </div>
                </form>


            </div>
        </div>
        <div class="col-sm-4"></div>
    </div>
</div>


{% endblock contenido %}

jardineria/jardineria_app/templates/crud/crearusuario.html
{% extends "crud/base.html" %}
{% load static %}
{% load crispy_forms_tags %}



{% block contenido %}
<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="p-5 border rounded shadow mt-4">
                <h3>Crear Usuario</h3>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{formulario | crispy}}

                    <div>
                        <input type="submit" value="Guardar Usuario" class="btn btn-success btn-lg">
                        <a href="{% url "dashboard" %}">
                        </br>
                            <button type="button" class="btn btn-light border btn-lg">Volver</button>
                        </a>
                    </div>
                </form>


            </div>
        </div>
        <div class="col-sm-4"></div>
    </div>
</div>


{% endblock contenido %}

jardineria/jardineria_app/templates/crud/detalles_pedidos_usuario.html
{% extends "crud/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}Detalle del Pedido{% endblock %}
{% block contenido %}
    <header id="header">
        <h1>Detalle del Pedido</h1>
    </header>

    <div class="detalle-pedido p-2 my-2">
        <h4>Usuario: {{ usuario.username }}</h4>
        <h4>Nombre: {{ usuario.first_name }} {{ usuario.last_name }}</h4>
        <h4>Dirección: {{ usuario.direccion }}</h4>
        <h4>RUT: {{ usuario.rut }}</h4>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Imagen</th>
                    <th scope="col">Producto</th>
                    <th scope="col">Valor</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Subtotal</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for detalle in detalles_pedidos %}
                <tr>
                    <td class="images"><img src="{{ detalle.producto.imagen.url }}" width="50px" height="50px"></td>
                    <td>{{ detalle.producto.nombre_producto }}</td>
                    <td>${{ detalle.producto.precio }}</td>
                    <td>{{ detalle.cantidad }}</td>
                    <td>${{ detalle.subtotal }}</td>
                    <td>
                        <form method="POST" action="{% url 'detalles_pedidos_usuario' usuario.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="pedido_id" value="{{ detalle.pedido.id }}">
                            <button type="submit" name="action" value="eliminar" class="btn btn-danger btn-sm">Eliminar</button>
                        </form>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6">No hay productos en tu pedido.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <h4>Total del pedido: ${{ total_pedido }}</h4>

        <a href="{% url 'listar_usuarios_con_pedidos' %}" class="btn btn-secondary btn-lg">Volver</a>
    </div>
{% endblock contenido %}

jardineria/jardineria_app/templates/crud/detalles_producto.html
{% extends "crud/base.html" %}
{% load static %}
{% block contenido %}
<div class="container mt-4">
    <div class="row">
        <div class="col-sm-4">            
        </div>
        <div class="col-sm-4">
            <div>
                <div class="card">                    
                    <div class="card-body">
                        <h2 class="card-title text-center">{{producto.nombre_producto}} {{producto.codigo_producto}}</h2>
                        <div class="p-2">
                            <img class="card-img-top" src="{{producto.imagen.url}}" alt="Foto" />
                        </div>                        
                        <p class="card-text"><span style="font-weight:bold;">Codigo Producto: </span>{{producto.codigo_producto}}</p>
                        <p class="card-text"><span style="font-weight:bold;">Tipo: </span>{{producto.tipo}}</p>
                        <p class="card-text"><span style="font-weight:bold;">Cantidad: </span>{{producto.cantidad}}</p>
                        <p class="card-text"><span style="font-weight:bold;">Precio: </span>{{producto.precio}}</p>
                    </div>
                    <div class="mt-3 mb-2 p-2">
                        {% if perms.jardineria.change_producto %}
                        <a href="{% url 'modificarproducto' producto.codigo_producto %}" role="button" class="btn btn-warning btn-lg text-light">Modificar</a>
                        {% endif %}
                        <a href="{% url 'productos' %}" role="button" class="btn btn-success border btn-lg">Volver</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4"></div>
    </div>
</div>
{% endblock contenido %}

jardineria/jardineria_app/templates/crud/detalles_usuario.html
{% extends "crud/base.html" %}
{% block contenido %}
<div class="container mt-4">
    <div class="row">
        <div class="col-sm-4">            
        </div>
        <div class="col-sm-4">
            <div>
                <div class="card">                    
                    <div class="card-body">
                        <h2 class="card-title text-center">{{ usuario.first_name }} {{ usuario.last_name }}</h2>
                        <p class="card-text"><span style="font-weight:bold;">ID: </span>{{ usuario.id }}</p>
                        <p class="card-text"><span style="font-weight:bold;">Nombre de Usuario: </span>{{ usuario.username }}</p>
                        <p class="card-text"><span style="font-weight:bold;">Email: </span>{{ usuario.email }}</p>
                        <p class="card-text"><span style="font-weight:bold;">RUT: </span>{{ usuario.rut }}</p>
                        <p class="card-text"><span style="font-weight:bold;">Dirección: </span>{{ usuario.direccion }}</p>
                    </div>
                    <div class="mt-3 mb-2 p-2">
                        {% if perms.auth.change_user %}
                        <a href="{% url 'modificar_usuario' usuario.id %}" role="button" class="btn btn-warning btn-lg text-light">Modificar</a>
                        {% endif %}
                        <a href="{% url 'listar_usuarios' %}" role="button" class="btn btn-success border btn-lg">Volver</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4"></div>
    </div>
</div>
{% endblock contenido %}

jardineria/jardineria_app/templates/crud/maceteros.html
{% extends 'crud/base.html' %}
{% load static %}

{% block titulo %}Productos de Maceteros{% endblock %}

{% block contenido %}
{% load humanize %}
<div class="container mt-4">
  <div class="row">
    <div class="col-sm-12">
      <h3>Productos de Maceteros Disponibles</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>IMAGEN</th>
            <th>NOMBRE PRODUCTO</th>
            <th>CANTIDAD</th>
            <th>TIPO</th>
            <th>PRECIO</th>
            <th>ACCIONES</th>
          </tr>
        </thead>
        <tbody>
          {% for p in productos_maceteros %}
          <tr>
            <td><img src="{{ p.imagen.url }}" alt="Imagen de {{ p.nombre_producto }}" height="100"></td>
            <td>{{ p.nombre_producto }}</td>
            <td>{{ p.cantidad }}</td>
            <td>{{ p.tipo }}</td>
            <td>{{ p.precio | intcomma }}</td>
            <td>
              <form method="post" action="{% url 'agregar_a_pedido' p.codigo_producto %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-success btn-sm text-light">Agregar al Carro</button>
              </form>
              {% if perms.jardineria.change_producto%}
                <a href="{% url "modificarproducto" p.codigo_producto %}" role="button" class="btn btn-warning btn-sm text-light mt-2">Modificar</a> </td>
                {% endif %}
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="6">No hay productos de maceteros disponibles.</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

jardineria/jardineria_app/templates/crud/modificaruser.html
{% extends "crud/base.html" %}
{% load static %}
{% load crispy_forms_tags %}



{% block contenido %}
<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="p-5 border rounded shadow mt-4">
                <h3>Editar Registro</h3>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form | crispy}}
                    <div>
                        <input type="submit" value="Modificar" class="btn btn-warning  text-light btn-lg">
                        <a href="{% url "dashboard" %}">
                            <button type="button" class="btn btn-success border btn-lg">Volver</button>
                        </a>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-sm-4"></div>
    </div>
</div>
{% endblock contenido %}

jardineria/jardineria_app/templates/crud/usuarios_con_pedidos.html
{% extends "crud/base.html" %}

{% block contenido %}
<div class="container mt-4">
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <h3>Listado de Usuarios con Pedidos</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Dirección</th>
            <th>Pedidos</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for usuario in usuarios %}
          <tr>
            <td>{{ usuario.id }}</td>
            <td>{{ usuario.username }}</td>
            <td>{{ usuario.direccion }}</td>
            <td>
              <ul>
                {% for pedido in usuario.pedido_set.all %}
                  <li>{{ pedido.producto.nombre_producto }} - Cantidad: {{ pedido.cantidad }}</li>
                {% endfor %}
              </ul>
            </td>
            <td>
              <a href="{% url 'detalles_pedidos_usuario' usuario.id %}" role="button" class="btn btn-info btn-sm text-light">Ver detalles del pedido</a>
              {% if perms.auth.change_user %}
              <a href="{% url 'agregar_pedido_usuario' usuario.id %}" role="button" class="btn btn-warning btn-sm text-light mt-2">Modificar pedido</a>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-sm-1"></div>
  </div>
</div>
{% endblock contenido %}